### ISSUE TITLE
Unable to use v1.1.1.1 in HUAWEI MATE20 Pro (EMUI9.1.0.135)

### ISSUE THREAD

**Issue by hkx303** [TonyJiangWJ/Ant-Forest-autoscript#3]
Hi,
1.1.1.0版本在华为MATE20 Pro EMUI9.1.0.135 无法正常使用
提示为：进入好友排行榜失败
日志信息：
![594460268](https://user-images.githubusercontent.com/46016760/70111608-bde01300-168d-11ea-8fd2-b4779b38194d.jpg)

**Comment by TonyJiangWJ** [comment]
升级一下最新版v1.1.1.1 修改了排行榜的判断

**Comment by hkx303** [comment]
Thanks for the quick reply :)

升级至`1.1.1.1`后，打开`蚂蚁森林`进入`总排行榜`后问题依旧；
日志信息：
![422246769](https://user-images.githubusercontent.com/46016760/70116320-56ca5a80-169d-11ea-91e1-f56f7bdd7668.jpg)

**Comment by TonyJiangWJ** [comment]
- 尝试删除`lib/WidgetUtils.js`中`line:99` 代码`idMatches(idRegex).findOne()`
- 通过布局范围分析，查找好友列表中有没有控件id匹配正则 `/.*react-content.*/`，默认配置的是 排行榜布局中最顶上 个人信息控件区域的id 如果你的不同 修改`config.js line: 99`相应的值`friend_list_id: '.*react-content.*',`

**Comment by hkx303** [comment]
Thanks for the detailed solution, I will try this and give feedback

**Comment by hkx303** [comment]
Hi,
通过`查看更多好友`进入`排行榜`后，通过布局范围分析
我发现页面仅剩下如下几个控件：
![1878001368](https://user-images.githubusercontent.com/46016760/70121634-f42b8b80-16a9-11ea-9e55-8cbca7777ff8.jpg)

这几个控件仅`返回`和`蚂蚁森林`控件有id，而且是蚂蚁森林初始页面都有的，有进一步的解决方案吗?

**Comment by hkx303** [comment]
更正：
上述 `返回` 控件初始页面没有，所以我把 `config.js line: 99` 的值`friend_list_id`替换为`'.*h5_nav_bak*'`
再次测试可以正常进入总排行榜页面，未再显示“无法进入好友排行榜”错误。
但是出现了新的错误：`获取能量值控件失败` 和`首次获取列表数据不完整，再次获取`，陷入死循环，无法停止。

**Comment by TonyJiangWJ** [comment]
- 上下两个大的区域，随便点按一个 进入 `在布局层次中查看`
- 从根节点开始查看是否有被隐藏掉的控件。如果没有那么很遗憾暂时没法使用这个脚本了。需要通过图片识别才行了
- 如果有，那可能还是可行的。只是会比较麻烦：总体思路是重新分析布局控件，获取到好友列表的控件。
- 首先是修改判断是否进入好友列表的方法`lib/WidgetUtils.js line:157`的 `friendListWaiting` 
  ```javascript
  /**
   * 校验是否成功进入好友排行榜
   */
  const friendListWaiting = function () {
    return idWaiting(_config.friend_list_id, '好友排行榜')
  }
  ```
- 然后替换掉`lib/WidgetUtils.js line:312`的 `getFriendListParent` 方法
  ```javascript
  const getFriendListParent = function getFriendRoot () {
    let anyone = null
    let regex = /[.\d]+[kgt]+$/
    let countdown = new Countdown()
    if (textMatches(regex).exists()) {
      anyone = textMatches(regex).findOnce(1)
      debugInfo('当前获取到的能量值内容：' + anyone.text())
    } else if (descMatches(regex).exists()) {
      debugInfo('当前获取到的能量值内容：' + anyone.desc())
      anyone = descMatches(regex).findOnce(1)
    }
    countdown.summary('获取能量值控件')
    if (anyone) {
      try {
        return anyone.parent().parent().parent()
      } catch (e) {
        errorInfo('获取能量值控件失败' + e)
      }
    } else {
      errorInfo('获取能量值控件失败')
    }
  }
  ```
- 后期有时间可能会加入图片识别，不过也可能会遥遥无期。目前很多功能都是基于控件的
- 由于我们的布局差异，我这边没法提供进一步的帮助了。祝成功~ ISSUE暂时就关闭了

**Comment by hkx303** [comment]
- 查看 `布局层次分析` ，没有发现被隐藏的控件
- 同意你说的说法，基于控件的脚本应该基本都无法使用，我想这也是[003作者脚本 ](https://github.com/SuperMonster003/Auto.js_Projects)进入排行榜后没有进一步动作的原因
- 谢谢耐心解释及提供的进一步方法
