### ISSUE TITLE
小米手机K20Pro-不自动进入蚂蚁森林

### ISSUE THREAD

**Issue by feng99** [TonyJiangWJ/Ant-Forest-autoscript#8]
已Star此项目

脚本版本V1.1.1.3
安卓版本 9
MIUI版本 11.0.4稳定版
问题现象:
       脚本打开支付宝后,不自动进入蚂蚁森林
需要手动点击蚂蚁森林图标    手动进入后
脚步才开始偷能量.
问题出现场景 : 定时偷能量时
手动偷能量  没有这个现象

**Comment by feng99** [comment]
[<a href="https://sm.ms/image/RtnClAcQELpqgu9" target="_blank"><img src="https://i.loli.net/2019/12/09/RtnClAcQELpqgu9.jpg" ></a>](url)

**Comment by feng99** [comment]
进入个人首页失败

**Comment by TonyJiangWJ** [comment]
看看AutoJS软件权限 有没有赋予 `后台弹出界面` 这个权限

**Comment by feng99** [comment]
> 看看AutoJS软件权限 有没有赋予 `后台弹出界面` 这个权限

谢谢,   **开启后台弹出界面**  权限后   解决了这个问题.
